### ISSUE TITLE
Missing python dependency to tdp_matomo

### ISSUE THREAD

**Issue by thinkh** [Caleydo/ordino#204]
* Release number or git hash: v5.1.0
* Environment (local or deployed): local

### Steps to reproduce

1. Setup or use an Ordino with tdp_matomo as indirect dependency 

### Observed behavior

Ordino calls the URL http://localhost:8080/api/tdp/config/matomo which results in an internal server error (error 500).

![image](https://user-images.githubusercontent.com/5851088/61391235-96460500-a8bc-11e9-92ba-4b1f3abba46e.png)

```
api_1       | 15:48:14 INFO phovea_server.server: init application: <Flask 'tdp_core.config'>
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 884, in handle_one_response
api_1       |     self.run_application()
api_1       |   File "/usr/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 88, in run_application
api_1       |     return super(WebSocketHandler, self).run_application()
api_1       |   File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 870, in run_application
api_1       |     self.result = self.application(self.environ, self.start_response)
api_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
api_1       |     return self.app(environ, start_response)
api_1       |   File "phovea_server/phovea_server/dispatcher.py", line 63, in __call__
api_1       |     return app(environ, start_response)
api_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
api_1       |     return self.wsgi_app(environ, start_response)
api_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
api_1       |     response = self.make_response(self.handle_exception(e))
api_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
api_1       |     reraise(exc_type, exc_value, tb)
api_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1       |     response = self.full_dispatch_request()
api_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
api_1       |     response = self.make_response(rv)
api_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1746, in make_response
api_1       |     rv = self.response_class.force_type(rv, request.environ)
api_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 885, in force_type
api_1       |     response = BaseResponse(*_run_wsgi_app(response, environ))
api_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
api_1       |     return _run_wsgi_app(*args)
api_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/test.py", line 884, in run_wsgi_app
api_1       |     app_rv = app(environ, start_response)
api_1       | TypeError: 'int' object is not callable
api_1       | {'GATEWAY_INTERFACE': 'CGI/1.1',
api_1       |  'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
api_1       |  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
api_1       |  'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
api_1       |  'HTTP_CACHE_CONTROL': 'max-age=0',
api_1       |  'HTTP_CONNECTION': 'close',
api_1       |  'HTTP_COOKIE': '_pk_id.2.1fff=4cc0f97ef6dfd43a.1551957657.1.1551960651.1551957657.; remember_token=admin|8b6a6d712455fe07cb24e7f6937e5b4e2366b96aed1ea7a5d9133752e2bffcccd57b394ca9c4ecae12db1e89ed62c96de463271f39f657d696a4e6c05db9cff1; cookiebar=CookieAllowed; io=5tIYF5J0TdAzYry1AAAN; randomCredentials=desperate_albattani@caqas4; session=.eJwljrEOgkAQRH_FbE2BhzYkFiYHhOKWQE7JXkM0oLDhLFBzesZ_F7Wa5s2beUFzmrprD_FtuncBNEML8QsWR4jBsApJb1coKyaReJT0QJlHSo-D4jwsdDUgG2tkKQzPDG-dqivGbGZEZWcmojq1yichfvsin12lI0HOaHJU7_m_sXPksS-yb9KKhOkVn59okyUKWqLOBekywrp8GL1bFzplI9NR-bNXNh3JJxt4B3C_dtPvPxxaO1zg_QHky0gx.EBDNtg.6RPQS_ZH7AEDnZEESWl3hGS-urc',
api_1       |  'HTTP_HOST': 'localhost:8080',
api_1       |  'HTTP_SEC_FETCH_MODE': 'navigate',
api_1       |  'HTTP_SEC_FETCH_SITE': 'none',
api_1       |  'HTTP_SEC_FETCH_USER': '?1',
api_1       |  'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
api_1       |  'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36',
api_1       |  'PATH_INFO': '/matomo',
api_1       |  'QUERY_STRING': '',
api_1       |  'REMOTE_ADDR': '172.21.0.1',
api_1       |  'REMOTE_PORT': '48150',
api_1       |  'REQUEST_METHOD': 'GET',
api_1       |  'SCRIPT_NAME': '/api/tdp/config',
api_1       |  'SERVER_NAME': '9438388b2e43',
api_1       |  'SERVER_PORT': '80',
api_1       |  'SERVER_PROTOCOL': 'HTTP/1.1',
api_1       |  'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
api_1       |  'werkzeug.proxy_fix.orig_http_host': 'localhost:8080',
api_1       |  'werkzeug.proxy_fix.orig_remote_addr': '172.21.0.1',
api_1       |  'werkzeug.proxy_fix.orig_wsgi_url_scheme': 'http',
api_1       |  'werkzeug.request': <Request 'http://localhost:8080/api/tdp/config/matomo' [GET]>,
api_1       |  'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f505f2871e0>,
api_1       |  'wsgi.input': <gevent.pywsgi.Input object at 0x7f50580d8050>,
api_1       |  'wsgi.multiprocess': False,
api_1       |  'wsgi.multithread': False,
api_1       |  'wsgi.run_once': False,
api_1       |  'wsgi.url_scheme': 'http',
api_1       |  'wsgi.version': (1, 0)} failed with TypeError
```

### Expected behavior
* No internal server error when calling the URL.
* Probably the server-side is missing in Ordino.

**Comment by thinkh** [comment]
We did not follow (and solve) the correct python dependency installation. This should be done in a separate setup/bugfix.

I close this PR as we do not need the switch from _app_ to _app-slib_ anymore for the TDP Matomo integration. We solved the integration using extension points in [tdp_matomo v2.0.0](https://github.com/datavisyn/tdp_matomo/pull/6).
