### ISSUE TITLE
[Bug] Build fails at npm install 

### ISSUE THREAD

**Issue by swkang73** [Caleydo/ordino#206]
* Release number or git hash: 1a29eef53cace7b9684f5a9cee65cab19f704c55

### Steps to reproduce

1. In my project repository, I've done the following command as specified in README:
```
git clone https://github.com/caleydo/ordino.git
cd ordino
npm install
```
2. But gets the following error:
```
npm WARN deprecated extract-text-webpack-plugin@2.1.0: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated @types/whatwg-fetch@0.0.33: fetch types are now provided by '--lib dom'

> fsevents@1.2.9 install [project directory]ordino/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "[project directory]ordino/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.7.2 install [project directory]ordino/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-64_binding.node": 


HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@2.6.9 postinstall [project directory]ordino/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.7.2 postinstall [project directory]ordino/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node [project directory]ordino/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '[project directory]ordino/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError ([project directory]ordino/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F ([project directory]ordino/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E ([project directory]ordino/node_modules/which/which.js:80:29)
gyp verb `which` failed     at [project directory]ordino/node_modules/which/which.js:89:16
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError ([project directory]ordino/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F ([project directory]ordino/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E ([project directory]ordino/node_modules/which/which.js:80:29)
gyp verb `which` failed     at [project directory]ordino/node_modules/which/which.js:89:16
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError ([project directory]ordino/node_modules/which/which.js:13:12)\n    at F ([project directory]ordino/node_modules/which/which.js:68:19)\n    at E ([project directory]ordino/node_modules/which/which.js:80:29)\n    at [project directory]ordino/node_modules/which/which.js:89:16\n    at [project directory]ordino/node_modules/isexe/index.js:42:5\n    at [project directory]ordino/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /Users/sunwookang/venv/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/sunwookang/venv/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "[project directory]ordino/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd [project directory]ordino/node_modules/node-sass
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunwookang/.npm/_logs/2019-08-16T16_18_44_708Z-debug.log

npm WARN deprecated extract-text-webpack-plugin@2.1.0: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated @types/whatwg-fetch@0.0.33: fetch types are now provided by '--lib dom'

> fsevents@1.2.9 install [project directory]ordino/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "[project directory]ordino/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.7.2 install [project directory]ordino/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/darwin-x64-64_binding.node": 


HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@2.6.9 postinstall [project directory]ordino/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.7.2 postinstall [project directory]ordino/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node [project directory]ordino/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '[project directory]ordino/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError ([project directory]ordino/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F ([project directory]ordino/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E ([project directory]ordino/node_modules/which/which.js:80:29)
gyp verb `which` failed     at [project directory]ordino/node_modules/which/which.js:89:16
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError ([project directory]ordino/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F ([project directory]ordino/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E ([project directory]ordino/node_modules/which/which.js:80:29)
gyp verb `which` failed     at [project directory]ordino/node_modules/which/which.js:89:16
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at [project directory]ordino/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError ([project directory]ordino/node_modules/which/which.js:13:12)\n    at F ([project directory]ordino/node_modules/which/which.js:68:19)\n    at E ([project directory]ordino/node_modules/which/which.js:80:29)\n    at [project directory]ordino/node_modules/which/which.js:89:16\n    at [project directory]ordino/node_modules/isexe/index.js:42:5\n    at [project directory]ordino/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /Users/sunwookang/venv/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/sunwookang/venv/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "[project directory]ordino/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd [project directory]ordino/node_modules/node-sass
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunwookang/.npm/_logs/2019-08-16T16_18_44_708Z-debug.log
```

### Observed behavior
I'm guessing the file is not python 3 compatible - since python2 is about to be deprecated next year, I would like to suggest adding support for python3 as well. 

### Expected behavior
I just want to troubleshoot and check out ordino project.

**Comment by thinkh** [comment]
Hi @swkang73,

thanks for giving Ordino a try. We are currently working on updating our framework and Ordino to Python 3. We will let you know here, as soon as we finish the update in a few weeks.

If you "just" want to try Ordino locally, I recommend to try the [Ordino Starter](https://github.com/Caleydo/ordino_starter) with some pre-loaded toy data. Please note that Ordino is open source, but the database itself is not.
