### ISSUE TITLE
Uncaught React error after switching repo to ESLint

### ISSUE THREAD

**Issue by dvdanielrehberger** [Caleydo/ordino#358]
* Release number or git hash: https://github.com/Caleydo/ordino/tree/dr/eslint - based on develop
* Web browser version and OS: Chrome & Ubuntu
* Environment (local or deployed): local

### Steps to reproduce

1. Start Ordino
2. Press the `Start Analysis` button

### Observed behavior
![image.png](https://images.zenhubusercontent.com/5f4e32206bdfe855e9e92a9c/f431c944-b9f6-4b5f-bdfe-06588e6f65f0)

    Uncaught Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in Unknown (created by StartMenuTabWrapper)
    in div (created by StartMenuTabWrapper)
    in div (created by StartMenuTabWrapper)
    in StartMenuTabWrapper (created by StartMenuComponent)
    in StartMenuComponent (created by OrdinoApp)
    in OrdinoApp
    at throwOnInvalidObjectType (react-dom.development.js:13413:1)
    at reconcileChildFibers (react-dom.development.js:14313:1)
    at reconcileChildren (react-dom.development.js:16762:1)
    at mountIndeterminateComponent (react-dom.development.js:17542:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22154:1)

**Comment by dvdanielrehberger** [comment]
Fixed now.
