### ISSUE TITLE
Open second view is broken after visyn script merge

### ISSUE THREAD

**Issue by thinkh** [Caleydo/ordino#424]
### Environment

 * Release number or git hash: https://github.com/Caleydo/ordino/commit/ec9c918d9c796d2eb1087c7131322dc8464eb367
 * Browser: Chrome 104
 * Deployed / Local: both
---

### Steps to reproduce the bug

0. https://ordino-daily.caleydoapp.org/app/?
1. Open a list of genes
2. Select genes
3. Open any second view

### Observed Behavior

The second view does not open. The dev console shows the following error.

```
ViewWrapper.ts:343 Uncaught (in promise) TypeError: $app.scrollTo is not a function
    at ViewWrapper.scrollIntoView (ViewWrapper.ts:343:17)
    at ViewWrapper.modeChanged (ViewWrapper.ts:324:12)
    at set mode [as mode] (ViewWrapper.ts:422:10)
    at OrdinoApp.tsx:494:7
    at Array.forEach (<anonymous>)
    at OrdinoApp.focusImpl (OrdinoApp.tsx:484:22)
    at OrdinoApp.tsx:411:53
    at async ActionNode.createViewImpl [as f] (cmds.ts:67:22)
```

### Expected Behavior

Switching to the second view should be possible again without an error.

Thanks for taking the time to fill out this bug report 🤗
Make sure there aren't any open/closed issues for this topic 😃

**Comment by thinkh** [comment]
With the visyn script merge (#421) the resolution of node modules has changed. That is probably the reason why jQuery plugins like `scrollTo` are not correctly loaded or registered to the "correct" jQuery instance. That's why the `scrollTo` function / plugin cannot be found and results in the error above.
